server:
  port: 8082

spring:
# database 연동 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/db_review?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#   mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: db_review_user
    password: 1234
  thymeleaf:
    cache: false

# spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
